---
config_dir: "{{ ansible_facts['user_dir'] }}/.config"
ansible_user: "sxavity"

distro_name: "{{ ansible_facts['distribution'] | lower }}"

git_email: "samuel.istnd@gmail.com"
git_name: "Samuel"

timezone: "Asia/Jakarta"
keyboard_layout: "us"

font_packages:
  - ttf-jetbrains-mono-nerd
