---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true

- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true
