---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  register: zsh_package

- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
  become: true

- name: Fetch oh-my-zsh
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh.sh
    mode: "0755"
  when: zsh_package.changed

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: /tmp/oh-my-zsh.sh --skip-chsh
  when: zsh_package.changed
