[theme]
mode = "dark"
source = "custom"
custom_palette = "everblush"

[bar.default]
position = "top"
background_opacity = 0.0
shadow = false
capsule = true
capsule_fill = "surface_variant"
capsule_border = "outline"
start  = ["workspaces"]
center = []
end    = ["clock", "notifications", "clipboard", "network", "volume", "brightness", "battery", "session"]

[widget.workspaces]
show_labels = true
focused_color = "#b3b9b8"
occupied_color = "#232a2d"
empty_color = "#232a2d"

[widget.clock]
capsule_padding = 12
