---
- name: Fetch uv install script
  ansible.builtin.uri:
    uri: https://astral.sh/uv/install.sh
    dest: /tmp/uv-install.sh
    mode: "0755"

- name: Install uv
  ansible.builtin.shell:
    cmd: /tmp/uv-install.sh
