---
- name: Ensure dnf-plugins-core is installed
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present

- name: Enable mise COPR repository
  become: true
  community.general.copr:
    name: jdxcode/mise
    state: enabled

- name: Install mise
  become: true
  ansible.builtin.dnf:
    name: mise
    state: present
