---
- name: Ensure extrepo is installed
  become: true
  ansible.builtin.apt:
    name: extrepo
    state: present
    update_cache: true

- name: Enable mise extrepo repository
  become: true
  ansible.builtin.command: extrepo enable mise
  args:
    creates: /etc/apt/sources.list.d/extrepo_mise.sources

- name: Install mise
  become: true
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: true
