import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const thinkingLevelMap = {
  off: "none",
  minimal: null,
  low: "low",
  medium: "medium",
  high: "high",
  xhigh: null,
  max: "high",
};

const compat = {
  supportsDeveloperRole: false,
  supportsReasoningEffort: true,
};

export default function (pi: ExtensionAPI) {
  pi.registerProvider("crofai", {
    name: "CrofAI",
    baseUrl: "https://crof.ai/v1",
    apiKey: "$CROFAI_API_KEY",
    api: "openai-completions",
    models: [
      {
        id: "deepseek-v4-pro-0813",
        name: "DeepSeek V4 Pro 0813",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.35, output: 0.8, cacheRead: 0.01, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.35, output: 0.8, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "deepseek-v4-flash-0731",
        name: "DeepSeek V4 Flash 0731",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.12, output: 0.21, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.12, output: 0.21, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "deepseek-v3.2",
        name: "DeepSeek V3.2",
        reasoning: false,
        ...compat,
        input: ["text"],
        cost: { input: 0.18, output: 0.35, cacheRead: 0.04, cacheWrite: 0 },
        contextWindow: 163_840,
        maxTokens: 163_840,
      },
      {
        id: "kimi-k3",
        name: "Kimi K3",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 2.0, output: 8.0, cacheRead: 0.25, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 262_144,
      },
      {
        id: "kimi-k3-eco",
        name: "Kimi K3 (Eco)",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 1.0, output: 4.0, cacheRead: 0.1, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.55, output: 2.25, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.5, output: 1.99, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "greg-2-ultra",
        name: "Greg 2 Ultra",
        reasoning: false,
        ...compat,
        input: ["text"],
        cost: { input: 3.0, output: 10.0, cacheRead: 0.5, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-2-super",
        name: "Greg 2 Super",
        reasoning: false,
        ...compat,
        input: ["text"],
        cost: { input: 1.5, output: 5.0, cacheRead: 0.25, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-1-mini",
        name: "Greg 1 Mini",
        reasoning: false,
        ...compat,
        input: ["text"],
        cost: { input: 0.07, output: 0.15, cacheRead: 0.01, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "greg-rp",
        name: "Greg (Roleplay)",
        reasoning: false,
        ...compat,
        input: ["text"],
        cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 229_376,
        maxTokens: 229_376,
      },
      {
        id: "mimo-v2.5-pro",
        name: "MiMo-V2.5-Pro",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.4, output: 0.8, cacheRead: 0.003, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "glm-5.2",
        name: "GLM 5.2",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.3, output: 1.05, cacheRead: 0.05, cacheWrite: 0 },
        contextWindow: 1_000_000,
        maxTokens: 131_072,
      },
      {
        id: "glm-5.1",
        name: "GLM 5.1",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.45, output: 2.15, cacheRead: 0.08, cacheWrite: 0 },
        contextWindow: 202_752,
        maxTokens: 202_752,
      },
      {
        id: "gemma-4-31b-it",
        name: "Gemma 4 31B",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "qwen3.8-27b",
        name: "Qwen3.8 27B",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.25, output: 2.1, cacheRead: 0.06, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "qwen3.6-27b",
        name: "Qwen3.6 27B",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.2, output: 1.5, cacheRead: 0.04, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "qwen3.5-397b-a17b",
        name: "Qwen3.5 397B A17B",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.35, output: 1.75, cacheRead: 0.07, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
      {
        id: "qwen3.5-9b",
        name: "Qwen3.5 9B",
        reasoning: true,
        thinkingLevelMap,
        ...compat,
        input: ["text"],
        cost: { input: 0.04, output: 0.15, cacheRead: 0.008, cacheWrite: 0 },
        contextWindow: 262_144,
        maxTokens: 262_144,
      },
    ],
  });
}
