---
target_packages:
  - git
  - wget
  - curl
  - less
  - nano
  - vim
  - htop
  - btop
  - jq
  - zip
  - unzip
  - tar
  - ripgrep
  - tmux
  - pass
  - stow
  - podman
  - brightnessctl
  - pipewire
  - pipewire-pulse
  - wireplumber
  - bluez
  - sway
  - waybar
  - dunst

distro_packages:
  ubuntu:
    - network-manager
    - fd-find
  archlinux:
    - networkmanager
    - fd
    - fastfetch
  fedora:
    - NetworkManager
    - fd-find
    - fastfetch

system_services:
  - bluetooth.service
  - NetworkManager.service

user_services:
  - pipewire.socket
  - pipewire-pulse.socket
  - wireplumber.service
  - podman.socket