---
target_packages:
  - git
  - wget
  - curl
  - less
  - nano
  - vim
  - htop
  - btop
  - jq
  - zip
  - unzip
  - tar
  - ripgrep
  - tmux
  - pass
  - stow
  - podman
  - brightnessctl
  - pipewire
  - wireplumber
  - bluez
  - neovim

distro_packages:
  ubuntu:
    - network-manager
    - fd-find
    - pipewire-pulse
  archlinux:
    - networkmanager
    - fd
    - fastfetch
    - pipewire-pulse
  fedora:
    - NetworkManager
    - fd-find
    - fastfetch
    - pipewire-pulseaudio
    - NetworkManager-wifi
    - alsa-sof-firmware
    - policycoreutils-python-utils
    - google-noto-sans-cjk-fonts
    - google-noto-serif-cjk-fonts
    - google-noto-emoji-fonts

system_services:
  - bluetooth.service
  - NetworkManager.service

user_services:
  - pipewire.socket
  - pipewire-pulse.socket
  - wireplumber.service
  - podman.socket
